### PR TITLE
Cleanup

### LINKED ISSUE #58: Cleanup
Do this - https://github.com/hapijs/contrib/issues/31

### PR DESCRIPTION
**Pull request by gergoerdosi**
Closes #58

### CODE REVIEW

**Comment by Marsup** [comment]
You should add the sudo part in travis while you're at it.

**Comment by gergoerdosi** [comment]
@Marsup Good suggestion, test was running for two hours. Added it now.

**Comment by Marsup** [comment]
No guarantee it'll help, I think travis is having problems.

**Comment by gergoerdosi** [comment]
Yes, they have an issue, legacy builds are affected, which is bad news for us. Status: https://www.traviscistatus.com/incidents/wf340mcz8zq0

**Comment by Marsup** [comment]
I've switched good to new builds, doesn't help, still waiting.

**Pull request merged**
